# Generated by Django 4.2 on 2023-06-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('dui_empleado', models.CharField(max_length=100, unique=True, verbose_name='Dui')),
                ('estatus', models.CharField(choices=[('EVENTUAL', 'EVENTUAL'), ('FIJO', 'FIJO')], default='FIJO', max_length=100, verbose_name='Estatus')),
                ('tel_empleado', models.CharField(blank=True, default='0000-0000', max_length=9, unique=True, verbose_name='Telefono')),
                ('estado_empleado', models.BooleanField(default=True, verbose_name='Estado Del Empleado')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El ')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
