# Generated by Django 4.2 on 2023-06-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='dui_empleado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='tel_empleado',
        ),
        migrations.AddField(
            model_name='empleados',
            name='observación',
            field=models.TextField(blank=True, verbose_name='Observación:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado El :'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estado_empleado',
            field=models.BooleanField(default=True, verbose_name='Estado Empleado:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estatus',
            field=models.CharField(choices=[('FIJO', 'FIJO'), ('EVENTUAL', 'EVENTUAL')], default='FIJO', max_length=100, verbose_name='Estatus:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre_empleado',
            field=models.CharField(max_length=100, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado El :'),
        ),
    ]
