# Generated by Django 4.2 on 2023-06-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_remove_empleados_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='estatus',
            field=models.CharField(choices=[('EVENTUAL', 'EVENTUAL'), ('FIJO', 'FIJO')], default='FIJO', max_length=100, verbose_name='Estatus:'),
        ),
        migrations.CreateModel(
            name='Asistencia_Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha :')),
                ('num_planilla', models.CharField(default='P', help_text='Numero De Planilla - Ejemplo:(P1)', max_length=100, verbose_name='Planilla:')),
                ('completado', models.BooleanField(default=True, verbose_name='completado:')),
                ('observación', models.TextField(blank=True, verbose_name='Observación:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El :')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El :')),
                ('empleados', models.ManyToManyField(to='asistencia.empleados', verbose_name='Añade Empleados:')),
            ],
            options={
                'verbose_name': 'Asistencia Diaria',
                'verbose_name_plural': 'Asistencias Diaria',
            },
        ),
    ]
