# Generated by Django 4.2 on 2023-06-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_empleados_estatus_asistencia_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='estatus',
            field=models.CharField(choices=[('PRESENTE', 'PRESENTE'), ('INC', 'INC'), ('AUSENTE', 'AUSENTE'), ('DESC', 'DESC'), ('PSG', 'PSG'), ('PCG', 'PCG')], max_length=100, verbose_name='Estatus:'),
        ),
    ]
