# Generated by Django 4.1.7 on 2023-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_empleados_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='estados',
            field=models.CharField(choices=[('INC', 'INC'), ('PSG', 'PSG'), ('DESC', 'DESC'), ('PRESENTE', 'PRESENTE'), ('AUSENTE', 'AUSENTE'), ('PCG', 'PCG')], default=1, max_length=100, verbose_name='Estatus:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estatus',
            field=models.CharField(choices=[('EVENTUAL', 'EVENTUAL'), ('FIJO', 'FIJO')], default='FIJO', max_length=100, verbose_name='Estatus:'),
        ),
    ]
