# Generated by Django 4.1.7 on 2023-06-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_empleados_estados_alter_empleados_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia_diaria',
            name='fecha_final',
            field=models.CharField(default=1, editable=False, max_length=100, verbose_name='Fecha:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estados',
            field=models.CharField(choices=[('AUSENTE', 'AUSENTE'), ('PCG', 'PCG'), ('DESC', 'DESC'), ('INC', 'INC'), ('PRESENTE', 'PRESENTE'), ('PSG', 'PSG')], max_length=100, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estatus',
            field=models.CharField(choices=[('FIJO', 'FIJO'), ('EVENTUAL', 'EVENTUAL')], default='FIJO', max_length=100, verbose_name='Estatus:'),
        ),
    ]
