# Generated by Django 4.1.7 on 2023-06-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_asistencia_diaria_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='estados',
        ),
        migrations.DeleteModel(
            name='Asistencia_Diaria',
        ),
    ]
