# Generated by Django 4.1.7 on 2023-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_remove_empleados_estados_delete_asistencia_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='numero_empleado',
            field=models.IntegerField(default=1, verbose_name='NO° De Empleado:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estatus',
            field=models.CharField(choices=[('EVENTUAL', 'EVENTUAL'), ('FIJO', 'FIJO')], default='FIJO', max_length=100, verbose_name='Estatus:'),
        ),
    ]
