# Generated by Django 4.1.7 on 2023-06-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_empleados_numero_empleado_alter_empleados_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='numero_empleado',
            field=models.IntegerField(verbose_name='N° De Empleado:'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', editable=False, max_length=100, verbose_name='Fecha :')),
                ('fecha', models.CharField(default='08/06/23', max_length=100, verbose_name='Fecha :')),
                ('estado', models.CharField(choices=[('AUSENTE', 'AUSENTE'), ('INC', 'INC'), ('PRESENTE', 'PRESENTE'), ('DESC', 'DESC'), ('PCG', 'PCG'), ('PSG', 'PSG')], max_length=100, verbose_name='Estado:')),
                ('num_planilla', models.CharField(default='P', help_text='Numero De Planilla - Ejemplo:(P1)', max_length=100, verbose_name='Planilla:')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El :')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El :')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opcion1', to='asistencia.empleados', verbose_name='Empleado:')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
