# Generated by Django 4.1.7 on 2023-06-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_alter_empleados_numero_empleado_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='empleado',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('INC', 'INC'), ('DESC', 'DESC'), ('AUSENTE', 'AUSENTE'), ('PRESENTE', 'PRESENTE'), ('PSG', 'PSG'), ('PCG', 'PCG')], max_length=100, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='nombre',
            field=models.CharField(default='', editable=False, max_length=100, verbose_name='Empleado:'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='empleado',
            field=models.ManyToManyField(related_name='opcion1', to='asistencia.empleados', verbose_name='Empleado:'),
        ),
    ]
