# Generated by Django 4.1.7 on 2023-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0012_asistencia_titulo_asistencia_alter_asistencia_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='estado',
        ),
        migrations.AddField(
            model_name='empleados',
            name='estado',
            field=models.CharField(choices=[('PCG', 'PCG'), ('AUSENTE', 'AUSENTE'), ('DESC', 'DESC'), ('PSG', 'PSG'), ('PRESENTE', 'PRESENTE'), ('INC', 'INC')], default=1, max_length=100, verbose_name='Estado:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='empleado',
            field=models.ManyToManyField(default='', related_name='opcion1', to='asistencia.empleados', verbose_name='Empleado:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estatus',
            field=models.CharField(choices=[('FIJO', 'FIJO'), ('EVENTUAL', 'EVENTUAL')], default='FIJO', max_length=100, verbose_name='Estatus:'),
        ),
    ]
