# Generated by Django 4.1.7 on 2023-06-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0014_empleado_datos_alter_empleados_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='estado_empleado',
        ),
        migrations.AddField(
            model_name='empleado_datos',
            name='estado_empleado',
            field=models.BooleanField(default=True, verbose_name='Estado Empleado:'),
        ),
        migrations.AddField(
            model_name='empleado_datos',
            name='observación',
            field=models.TextField(blank=True, verbose_name='Observación:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='departamento',
            field=models.CharField(choices=[('PRODUCCION', 'PRODUCCION'), ('RASTRA', 'RASTRA'), ('ADMINISTRACION', 'ADMINISTRACION')], default='RASTRA', max_length=100, verbose_name='Estatus:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estado',
            field=models.CharField(choices=[('DESC', 'DESC'), ('PSG', 'PSG'), ('INC', 'INC'), ('SAB.', 'SAB.'), ('VAC.', 'VAC.'), ('---', '---'), ('PCG', 'PCG'), ('X', 'X'), ('DOM.', 'DOM.')], max_length=100, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estatus',
            field=models.CharField(choices=[('FIJO', 'FIJO'), ('EVENTUAL', 'EVENTUAL')], default='FIJO', max_length=100, verbose_name='Estatus:'),
        ),
    ]
