# Generated by Django 4.1.7 on 2023-06-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0016_alter_empleado_datos_cargo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado_datos',
            old_name='nombre_empleado',
            new_name='nombre_empleado_dato',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='observación',
        ),
        migrations.AddField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(default='', editable=False, max_length=100, verbose_name='Empleado:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='cargo',
            field=models.CharField(choices=[('OPERARIO', 'OPERARIO'), ('MOZO CAMION', 'MOZO CAMION'), ('MOZO RASTRA', 'MOZO RASTRA')], default='OPERARIO', max_length=100, verbose_name='Cargo:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='departamento',
            field=models.CharField(choices=[('ADMINISTRACION', 'ADMINISTRACION'), ('PRODUCCION', 'PRODUCCION'), ('RASTRA', 'RASTRA')], default='RASTRA', max_length=100, verbose_name='Departamento:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estatus',
            field=models.CharField(choices=[('EVENTUAL', 'EVENTUAL'), ('FIJO', 'FIJO')], default='FIJO', max_length=100, verbose_name='Estatus:'),
        ),
    ]
