# Generated by Django 4.1.7 on 2023-06-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0018_remove_empleados_estatus_empleado_datos_estatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name': 'Asistencia 11 Al 25', 'verbose_name_plural': 'Asistencias 11 - 25'},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name': 'Estado Empleados', 'verbose_name_plural': 'Estados Empleados'},
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='numero_empleado',
        ),
        migrations.AddField(
            model_name='empleado_datos',
            name='numero_empleado',
            field=models.IntegerField(default=1, verbose_name='N° De Empleado:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='comentarios',
            field=models.TextField(blank=True, default='Asistencia Completada: 11/06/23', verbose_name='Comentarios:'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.CharField(default='11/06/23', max_length=100, verbose_name='Fecha :'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='titulo_asistencia',
            field=models.CharField(default='DIA - 11', help_text=' --No Cambie el formato--', max_length=100, verbose_name='Titulo Registro:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='cargo',
            field=models.CharField(choices=[('OPERARIO', 'OPERARIO'), ('MOZO CAMION', 'MOZO CAMION'), ('MOZO RASTRA', 'MOZO RASTRA')], default='OPERARIO', max_length=100, verbose_name='Cargo:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='departamento',
            field=models.CharField(choices=[('ADMINISTRACION', 'ADMINISTRACION'), ('PRODUCCION', 'PRODUCCION'), ('RASTRA', 'RASTRA')], default='RASTRA', max_length=100, verbose_name='Departamento:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='dia_ingreso',
            field=models.CharField(default='11/06/23', max_length=100, verbose_name='Fecha De Ingreso:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='estatus',
            field=models.CharField(choices=[('FIJO', 'FIJO'), ('EVENTUAL', 'EVENTUAL')], default='FIJO', max_length=100, verbose_name='Estatus:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estados',
            field=models.CharField(choices=[('PCG', 'PCG'), ('---', '---'), ('INC', 'INC'), ('DOM.', 'DOM.'), ('VAC.', 'VAC.'), ('SAB.', 'SAB.'), ('X', 'X'), ('PSG', 'PSG'), ('DESC', 'DESC')], default='FIJO', max_length=100, verbose_name='Estado:'),
        ),
    ]
