# Generated by Django 4.1.7 on 2023-06-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0019_alter_asistencia_options_alter_empleados_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='comentarios',
            field=models.TextField(blank=True, default='Asistencia Completada: 12/06/23', verbose_name='Comentarios:'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.CharField(default='12/06/23', max_length=100, verbose_name='Fecha :'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='titulo_asistencia',
            field=models.CharField(default='DIA - 12', help_text=' --No Cambie el formato--', max_length=100, verbose_name='Titulo Registro:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='cargo',
            field=models.CharField(choices=[('MOZO CAMION', 'MOZO CAMION'), ('OPERARIO', 'OPERARIO'), ('MOZO RASTRA', 'MOZO RASTRA')], default='OPERARIO', max_length=100, verbose_name='Cargo:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='departamento',
            field=models.CharField(choices=[('RASTRA', 'RASTRA'), ('ADMINISTRACION', 'ADMINISTRACION'), ('PRODUCCION', 'PRODUCCION')], default='RASTRA', max_length=100, verbose_name='Departamento:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='dia_ingreso',
            field=models.CharField(default='12/06/23', max_length=100, verbose_name='Fecha De Ingreso:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='estatus',
            field=models.CharField(choices=[('EVENTUAL', 'EVENTUAL'), ('FIJO', 'FIJO')], default='FIJO', max_length=100, verbose_name='Estatus:'),
        ),
        migrations.AlterField(
            model_name='empleado_datos',
            name='numero_empleado',
            field=models.IntegerField(verbose_name='N° Empleado:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estados',
            field=models.CharField(choices=[('X', 'X'), ('DESC', 'DESC'), ('PSG', 'PSG'), ('---', '---'), ('SAB.', 'SAB.'), ('VAC.', 'VAC.'), ('PCG', 'PCG'), ('DOM.', 'DOM.'), ('INC', 'INC')], default='FIJO', max_length=100, verbose_name='Estado:'),
        ),
        migrations.CreateModel(
            name='Asistencia2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_asistencia2', models.CharField(default='DIA - 12', help_text=' --No Cambie el formato--', max_length=100, verbose_name='Titulo Registro:')),
                ('fecha2', models.CharField(default='12/06/23', max_length=100, verbose_name='Fecha :')),
                ('num_planilla2', models.CharField(default='P', help_text='Numero De Planilla - Ejemplo:(P1)', max_length=100, verbose_name='Planilla:')),
                ('comentarios2', models.TextField(blank=True, default='Asistencia Completada: 12/06/23', verbose_name='Comentarios:')),
                ('created_at2', models.DateTimeField(auto_now_add=True, verbose_name='Creado El :')),
                ('updated_at2', models.DateTimeField(auto_now=True, verbose_name='Actualizado El :')),
                ('empleado2', models.ManyToManyField(default='', related_name='opcion2', to='asistencia.empleados', verbose_name='Empleado:')),
            ],
            options={
                'verbose_name': 'Asistencia 26 Al 10',
                'verbose_name_plural': 'Asistencias 26 - 10',
            },
        ),
    ]
